<?php

namespace common\modules\doc\controllers;

use common\dzbase\DzController;
use common\modules\doc\services\Route;
use yii\web\Controller;

/**
 * Default controller for the `api` module
 */
class DefaultController extends DzController
{
    public function init()
    {
        \Yii::$app->response->format = 'html';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $model = new Route();

        $routes =  $model->getRoutes();
        unset($routes['/*']);
        foreach ($routes as $key =>  &$route) {
            if (preg_match('#^/route|gii|debug/#', $key, $m)) {
                unset($routes[$key]);
            }
        }
        $routes = array_reverse($routes);
        return $this->renderPartial('index', [
            'routes'=>$routes
        ]);
    }


    public function actionRoutes()
    {
    }

    public function actionsTest()
    {
        echo 1;
    }
}
